create table if not exists public.cta_leads (
    id bigint generated by default as identity primary key,
    nama text not null,
    email text not null,
    nomor_whatsapp text not null,
    program_diminati text not null,
    sumber_informasi text not null,
    created_at timestamptz not null default now()
);

alter table public.cta_leads enable row level security;

drop policy if exists "Izinkan insert lead CTA" on public.cta_leads;

create policy "Izinkan insert lead CTA"
on public.cta_leads
for insert
with check (true);
